FROM horovod/horovod:0.18.1-tf1.14.0-torch1.2.0-mxnet1.5.0-py3.6

# add tsinghua
COPY proxy/sources.list /etc/apt/sources.list
COPY proxy/.pip/ /root/.pip/

RUN apt remove librdmacm1 libibverbs1 ibverbs-providers && rm -rf /etc/apt/sources.list.d* && apt clean && apt update && apt install udev libcap2 kmod libnuma1 && rm -rf /var/lib/apt/lists/*


# Download and install Mellanox OFED 5.0-1.0.0.0 for Ubuntu 16.04
 RUN wget http://content.mellanox.com/ofed/MLNX_OFED-5.0-1.0.0.0/MLNX_OFED_LINUX-5.0-1.0.0.0-ubuntu18.04-x86_64.tgz && \
    tar -xzvf MLNX_OFED_LINUX-5.0-1.0.0.0-ubuntu18.04-x86_64.tgz && \
    MLNX_OFED_LINUX-5.0-1.0.0.0-ubuntu18.04-x86_64/mlnxofedinstall --user-space-only --without-fw-update --all -q && \
    cd .. && \
    rm -rf MLNX_OFED_LINUX-5.0-1.0.0.0-ubuntu18.04-x86_64 && \
    rm -rf *.tgz
